/// Renders `catalog.dart` as the SQL that seeds version 1 of every template.
/// The output is committed as `migrations/0006_catalog_seed.sql` and a test
/// holds it to this renderer, so the seed and the Dart catalogue agree.
library;

import 'dart:convert';

import 'package:domain/domain.dart';

/// The date version 1 takes effect: before any card's first cycle, so every
/// cycle a linked card has ever had resolves against a version.
const seedEffectiveFrom = '2000-01-01';

const _source =
    'https://github.com/helpmebrands/reward-app/blob/develop/'
    'packages/domain/lib/src/catalog.dart';

String _text(Object? value) => switch (value) {
  null => 'NULL',
  final bool b => b ? 'true' : 'false',
  final int i => '$i',
  final String s => "'${s.replaceAll("'", "''")}'",
  _ => throw ArgumentError(value),
};

/// Every template but `blank`, which is how a household makes a card of its
/// own and is not part of the catalogue. Versions are inserted as drafts,
/// given their credits, then published, because a published version takes
/// no new credits.
String renderCatalogSeed(List<CardTemplate> templates) {
  final out = StringBuffer()
    ..writeln('-- Generated by tool/catalog_seed.dart from catalog.dart;')
    ..writeln('-- do not edit. Version 1 of every catalogue template.');
  for (final template in templates) {
    if (template.id == 'blank') continue;
    final id = _text(template.id);
    out
      ..writeln()
      ..writeln('INSERT INTO card_templates (id) VALUES ($id);')
      ..writeln(
        'INSERT INTO template_versions (template_id, version, '
        'effective_from, status, issuer, product, network, kind, '
        'annual_fee_cents) VALUES ($id, 1, ${_text(seedEffectiveFrom)}, '
        "'draft', ${_text(template.issuer)}, ${_text(template.product)}, "
        '${_text(template.network.name)}, ${_text(template.kind.name)}, '
        '${template.annualFeeCents});',
      );
    for (final (position, credit) in template.benefits.indexed) {
      final json = benefitTemplateToJson(credit);
      out.writeln(
        'INSERT INTO template_credits (template_id, version, credit_id, '
        'position, name, description, category, icon, merchant, '
        'value_cents, cadence, anchor, interval_months, '
        'enrollment_required, spend_threshold_cents, ends_on, '
        'redemption_steps, notes) VALUES ($id, 1, ${_text(credit.id)}, '
        '$position, ${_text(credit.name)}, ${_text(credit.description)}, '
        '${_text(json['category'])}, ${_text(credit.icon)}, '
        '${_text(credit.merchant)}, ${credit.valueCents}, '
        '${_text(credit.cadence.name)}, ${_text(credit.anchor.name)}, '
        '${_text(credit.intervalMonths)}, ${_text(credit.enrollmentRequired)}, '
        '${_text(credit.spendThresholdCents)}, ${_text(credit.endsOn)}, '
        '${_text(jsonEncode(credit.redemptionSteps))}, '
        '${_text(credit.notes)});',
      );
    }
    out.writeln(
      "UPDATE template_versions SET status = 'published', "
      "published_by = 'seed', published_at = now(), "
      "source_url = ${_text(_source)}, "
      "notes = 'Version 1, seeded from catalog.dart' "
      'WHERE template_id = $id AND version = 1;',
    );
  }
  return out.toString();
}
