import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

import { readPng } from './png'

// The native brand assets generated by apps/mobile/scripts/brand-icons.swift
// from assets/logo: what each platform reads at launch, checked by file,
// declared size and pixel format, since a wrong size is only noticed when
// Xcode or the Play console rejects the build.

const root = join(import.meta.dirname, '..', '..')
const ios = join(root, 'apps/mobile/ios/Runner/Assets.xcassets')
const res = join(root, 'apps/mobile/android/app/src/main/res')

const densities = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 } as const

interface IconEntry {
  filename?: string
  size: string
  scale?: string
  appearances?: { appearance: string; value: string }[]
}

describe('iOS app icon', () => {
  const set = join(ios, 'AppIcon.appiconset')
  const images = (): IconEntry[] =>
    JSON.parse(readFileSync(join(set, 'Contents.json'), 'utf8')).images

  // @lat: [[infra-tests#Brand icons#Every iOS icon file is the size it declares]]
  it('lists files that exist at the pixel size each declares', () => {
    const listed = images().filter((image) => image.filename)
    expect(listed.length).toBeGreaterThan(0)
    for (const image of listed) {
      const png = readPng(join(set, image.filename!))
      const points = Number(image.size.split('x')[0])
      const scale = Number((image.scale ?? '1x').replace('x', ''))
      expect(png.width, image.filename).toBe(points * scale)
      expect(png.height, image.filename).toBe(points * scale)
    }
  })

  // @lat: [[infra-tests#Brand icons#iOS has a dark appearance and an opaque 1024 icon]]
  it('has a dark-appearance icon and a 1024 icon without alpha', () => {
    const dark = images().filter((image) =>
      image.appearances?.some((a) => a.appearance === 'luminosity' && a.value === 'dark'),
    )
    expect(dark.length).toBeGreaterThan(0)
    expect(dark.every((image) => image.filename)).toBe(true)

    const marketing = images().filter(
      (image) => image.size === '1024x1024' && !image.appearances && image.filename,
    )
    expect(marketing.length).toBeGreaterThan(0)
    for (const image of marketing) {
      expect(readPng(join(set, image.filename!)).hasAlpha, image.filename).toBe(false)
    }
  })
})

/** Whether the pixel at (x, y) is the brand's maroon rather than, say, the
 * Flutter template's blue. */
function isMaroon(path: string, x: number, y: number): boolean {
  const png = readPng(path)
  const i = (y * png.width + x) * 4
  const [r, g, b, a] = png.pixels().subarray(i, i + 4)
  return a === 255 && r > g + 50 && r > b + 30
}

describe('the launcher icons are the brand', () => {
  // @lat: [[infra-tests#Brand icons#The launcher icons are the brand's maroon]]
  it('draws the maroon icon on iOS and Android', () => {
    expect(isMaroon(join(ios, 'AppIcon.appiconset/Icon-App-1024x1024@1x.png'), 8, 512)).toBe(true)
    expect(isMaroon(join(res, 'mipmap-xxxhdpi/ic_launcher.png'), 8, 96)).toBe(true)
  })
})

describe('Android launcher icon', () => {
  // @lat: [[infra-tests#Brand icons#Each Android density has its launcher size]]
  it('has ic_launcher.png at 48dp in every density', () => {
    for (const [density, factor] of Object.entries(densities)) {
      const png = readPng(join(res, `mipmap-${density}`, 'ic_launcher.png'))
      expect(png.width, density).toBe(48 * factor)
      expect(png.height, density).toBe(48 * factor)
    }
  })

  // @lat: [[infra-tests#Brand icons#The adaptive icon has all three layers]]
  it('declares an adaptive icon with foreground, background and monochrome', () => {
    const xml = readFileSync(join(res, 'mipmap-anydpi-v26', 'ic_launcher.xml'), 'utf8')
    for (const layer of ['background', 'foreground', 'monochrome']) {
      const match = xml.match(new RegExp(`<${layer}[^>]*android:drawable="@(\\w+)/(\\w+)"`))
      expect(match, layer).not.toBeNull()
      const [, kind, name] = match!
      const found = Object.keys(densities).some((d) =>
        existsSync(join(res, `${kind}-${d}`, `${name}.png`)),
      ) || existsSync(join(res, kind, `${name}.xml`))
      expect(found, `${layer} @${kind}/${name}`).toBe(true)
    }
  })
})

/** The Nocturne page colour for [theme], read from the app's tokens so the
 * native splash cannot drift from the first Flutter frame. */
function pageColour(theme: 'dark' | 'light'): string {
  const tokens = readFileSync(join(root, 'apps/mobile/lib/theme/nocturne_tokens.dart'), 'utf8')
  const block = tokens.split(`static const NocturneTokens ${theme} = NocturneTokens(`)[1]
  const argb = block.match(/background: Color\(0xFF([0-9A-F]{6})\)/)![1]
  return `#${argb}`
}

/** A style item's value, with an `@color/` reference resolved against the
 * colours of the same night qualifier. */
function styleItem(values: string, name: string): string | undefined {
  const xml = readFileSync(join(res, values, 'styles.xml'), 'utf8')
  const value = xml.match(new RegExp(`<item name="${name}">([^<]+)</item>`))?.[1].trim()
  const ref = value?.match(/^@color\/(\w+)$/)
  if (!ref) return value
  const night = values.includes('night') ? 'values-night' : 'values'
  const colours = readFileSync(join(res, night, 'colors.xml'), 'utf8')
  return colours.match(new RegExp(`<color name="${ref[1]}">([^<]+)</color>`))?.[1].trim()
}

describe('launch screen', () => {
  const storyboard = () =>
    readFileSync(join(root, 'apps/mobile/ios/Runner/Base.lproj/LaunchScreen.storyboard'), 'utf8')

  // @lat: [[infra-tests#Brand icons#The iOS launch screen shows the icon on the page colour]]
  it('draws the icon image set on the page colour for each appearance', () => {
    const images = [...storyboard().matchAll(/<imageView[^>]* image="(\w+)"/g)].map((m) => m[1])
    expect(images).toEqual(['LaunchIcon'])
    const set = join(ios, 'LaunchIcon.imageset')
    const entries: IconEntry[] = JSON.parse(readFileSync(join(set, 'Contents.json'), 'utf8')).images
    expect(entries.map((e) => e.scale).sort()).toEqual(['1x', '2x', '3x'])
    const base = readPng(join(set, entries.find((e) => e.scale === '1x')!.filename!)).width
    for (const entry of entries) {
      const png = readPng(join(set, entry.filename!))
      expect(png.width, entry.filename).toBe(base * Number(entry.scale!.replace('x', '')))
    }
    expect(existsSync(join(ios, 'LaunchImage.imageset'))).toBe(false)

    const named = storyboard().match(/<color key="backgroundColor" name="(\w+)"/)?.[1]
    expect(named).toBe('LaunchBackground')
    const colours = JSON.parse(
      readFileSync(join(ios, `${named}.colorset`, 'Contents.json'), 'utf8'),
    ).colors as { appearances?: { value: string }[]; color: { components: Record<string, string> } }[]
    const hexOf = (c: (typeof colours)[number]) =>
      '#' + ['red', 'green', 'blue'].map((k) => c.color.components[k].replace('0x', '')).join('').toUpperCase()
    expect(hexOf(colours.find((c) => !c.appearances)!)).toBe(pageColour('light'))
    expect(hexOf(colours.find((c) => c.appearances?.[0].value === 'dark')!)).toBe(pageColour('dark'))
  })

  // @lat: [[infra-tests#Brand icons#Android 12 splashes set the icon and the page colour]]
  it('sets the Android 12 splash icon and background in both themes', () => {
    for (const [values, theme] of [['values-v31', 'light'], ['values-night-v31', 'dark']] as const) {
      const icon = styleItem(values, 'android:windowSplashScreenAnimatedIcon')
      expect(icon, values).toMatch(/^@drawable\/\w+$/)
      const name = icon!.split('/')[1]
      expect(
        Object.keys(densities).some((d) => existsSync(join(res, `drawable-${d}`, `${name}.png`))),
        `${values} ${icon}`,
      ).toBe(true)
      expect(styleItem(values, 'android:windowSplashScreenBackground')?.toUpperCase(), values).toBe(
        pageColour(theme),
      )
    }
  })

  // @lat: [[infra-tests#Brand icons#Older Android draws the icon on the page colour]]
  it('draws the icon on the page colour before Android 12', () => {
    for (const drawable of ['drawable', 'drawable-v21']) {
      const xml = readFileSync(join(res, drawable, 'launch_background.xml'), 'utf8')
      expect(xml, drawable).toContain('@color/splash_background')
      expect(xml, drawable).toMatch(/<bitmap[^>]*android:src="@drawable\/splash_icon"/)
    }
    for (const [values, theme] of [['values', 'light'], ['values-night', 'dark']] as const) {
      const colours = readFileSync(join(res, values, 'colors.xml'), 'utf8')
      expect(colours.match(/<color name="splash_background">([^<]+)<\/color>/)?.[1].toUpperCase()).toBe(
        pageColour(theme),
      )
    }
  })
})
