import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

import { readPng } from './png'

// The native brand assets generated by apps/mobile/scripts/brand-icons.swift
// from assets/logo: what each platform reads at launch, checked by file,
// declared size and pixel format, since a wrong size is only noticed when
// Xcode or the Play console rejects the build.

const root = join(import.meta.dirname, '..', '..')
const ios = join(root, 'apps/mobile/ios/Runner/Assets.xcassets')
const res = join(root, 'apps/mobile/android/app/src/main/res')

const densities = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 } as const

interface IconEntry {
  filename?: string
  size: string
  scale?: string
  appearances?: { appearance: string; value: string }[]
}

describe('iOS app icon', () => {
  const set = join(ios, 'AppIcon.appiconset')
  const images = (): IconEntry[] =>
    JSON.parse(readFileSync(join(set, 'Contents.json'), 'utf8')).images

  // @lat: [[infra-tests#Brand icons#Every iOS icon file is the size it declares]]
  it('lists files that exist at the pixel size each declares', () => {
    const listed = images().filter((image) => image.filename)
    expect(listed.length).toBeGreaterThan(0)
    for (const image of listed) {
      const png = readPng(join(set, image.filename!))
      const points = Number(image.size.split('x')[0])
      const scale = Number((image.scale ?? '1x').replace('x', ''))
      expect(png.width, image.filename).toBe(points * scale)
      expect(png.height, image.filename).toBe(points * scale)
    }
  })

  // @lat: [[infra-tests#Brand icons#iOS has a dark appearance and an opaque 1024 icon]]
  it('has a dark-appearance icon and a 1024 icon without alpha', () => {
    const dark = images().filter((image) =>
      image.appearances?.some((a) => a.appearance === 'luminosity' && a.value === 'dark'),
    )
    expect(dark.length).toBeGreaterThan(0)
    expect(dark.every((image) => image.filename)).toBe(true)

    const marketing = images().filter(
      (image) => image.size === '1024x1024' && !image.appearances && image.filename,
    )
    expect(marketing.length).toBeGreaterThan(0)
    for (const image of marketing) {
      expect(readPng(join(set, image.filename!)).hasAlpha, image.filename).toBe(false)
    }
  })
})

/** Whether the pixel at (x, y) is the brand's maroon rather than, say, the
 * Flutter template's blue. */
function isMaroon(path: string, x: number, y: number): boolean {
  const png = readPng(path)
  const i = (y * png.width + x) * 4
  const [r, g, b, a] = png.pixels().subarray(i, i + 4)
  return a === 255 && r > g + 50 && r > b + 30
}

describe('the launcher icons are the brand', () => {
  // @lat: [[infra-tests#Brand icons#The launcher icons are the brand's maroon]]
  it('draws the maroon icon on iOS and Android', () => {
    expect(isMaroon(join(ios, 'AppIcon.appiconset/Icon-App-1024x1024@1x.png'), 8, 512)).toBe(true)
    expect(isMaroon(join(res, 'mipmap-xxxhdpi/ic_launcher.png'), 8, 96)).toBe(true)
  })
})

describe('Android launcher icon', () => {
  // @lat: [[infra-tests#Brand icons#Each Android density has its launcher size]]
  it('has ic_launcher.png at 48dp in every density', () => {
    for (const [density, factor] of Object.entries(densities)) {
      const png = readPng(join(res, `mipmap-${density}`, 'ic_launcher.png'))
      expect(png.width, density).toBe(48 * factor)
      expect(png.height, density).toBe(48 * factor)
    }
  })

  // @lat: [[infra-tests#Brand icons#The adaptive icon has all three layers]]
  it('declares an adaptive icon with foreground, background and monochrome', () => {
    const xml = readFileSync(join(res, 'mipmap-anydpi-v26', 'ic_launcher.xml'), 'utf8')
    for (const layer of ['background', 'foreground', 'monochrome']) {
      const match = xml.match(new RegExp(`<${layer}[^>]*android:drawable="@(\\w+)/(\\w+)"`))
      expect(match, layer).not.toBeNull()
      const [, kind, name] = match!
      const found = Object.keys(densities).some((d) =>
        existsSync(join(res, `${kind}-${d}`, `${name}.png`)),
      ) || existsSync(join(res, kind, `${name}.xml`))
      expect(found, `${layer} @${kind}/${name}`).toBe(true)
    }
  })
})
