/**
 * Emits packages/domain/lib/src/catalog.dart from the catalogue in this
 * package, so the two implementations share one list of templates:
 *
 *   node --experimental-strip-types scripts/emit-catalog.ts \
 *     > ../../packages/domain/lib/src/catalog.dart && fvm dart format ../../packages/domain
 */
import { CARD_TEMPLATES } from '../src/domain/catalog.ts'

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$')}'`
const cat = (c: string) => (c === 'fee_credit' ? 'feeCredit' : c)
const out: string[] = []
out.push('/// The card catalogue behind "Add a card".')
out.push('///')
out.push('/// Issuers change these terms constantly, so this is a starting point for')
out.push('/// onboarding, not a source of truth: everything it creates is an ordinary')
out.push('/// editable credit, and the add-card flow says so. `enrollmentRequired` is')
out.push('/// the field worth getting right: it is the difference between a credit the')
out.push('/// user is failing to spend and one they cannot spend at all.')
out.push('///')
out.push("/// The templates are generated from the PWA's `src/domain/catalog.ts` by")
out.push('/// `apps/pwa/scripts/emit-catalog.ts`; edit there and regenerate.')
out.push('library;')
out.push('')
out.push("import 'types.dart';")
out.push('')
out.push('class BenefitTemplate {')
out.push('  const BenefitTemplate({')
out.push('    required this.name,')
out.push('    this.description,')
out.push('    required this.category,')
out.push('    required this.icon,')
out.push('    this.merchant,')
out.push('    required this.valueCents,')
out.push('    required this.cadence,')
out.push('    required this.anchor,')
out.push('    this.enrollmentRequired = false,')
out.push('    this.redemptionSteps = const [],')
out.push('    this.notes,')
out.push('  });')
out.push('')
out.push('  final String name;')
out.push('  final String? description;')
out.push('  final BenefitCategory category;')
out.push('')
out.push('  /// Icon name.')
out.push('  final String icon;')
out.push('  final String? merchant;')
out.push('  final int valueCents;')
out.push('  final Cadence cadence;')
out.push('  final CycleAnchor anchor;')
out.push('  final bool enrollmentRequired;')
out.push('  final List<String> redemptionSteps;')
out.push('  final String? notes;')
out.push('}')
out.push('')
out.push('class CardTemplate {')
out.push('  const CardTemplate({')
out.push('    required this.id,')
out.push('    required this.issuer,')
out.push('    required this.product,')
out.push('    required this.network,')
out.push('    required this.annualFeeCents,')
out.push('    required this.benefits,')
out.push('  });')
out.push('')
out.push('  final String id;')
out.push('  final String issuer;')
out.push('  final String product;')
out.push('  final CardNetwork network;')
out.push('  final int annualFeeCents;')
out.push('  final List<BenefitTemplate> benefits;')
out.push('}')
out.push('')
out.push('const List<CardTemplate> cardTemplates = [')
for (const t of CARD_TEMPLATES) {
  out.push('  CardTemplate(')
  out.push(`    id: ${q(t.id)},`)
  out.push(`    issuer: ${q(t.issuer)},`)
  out.push(`    product: ${q(t.product)},`)
  out.push(`    network: CardNetwork.${t.network},`)
  out.push(`    annualFeeCents: ${t.annualFeeCents},`)
  out.push('    benefits: [')
  for (const b of t.benefits) {
    out.push('      BenefitTemplate(')
    out.push(`        name: ${q(b.name)},`)
    if (b.description) out.push(`        description: ${q(b.description)},`)
    out.push(`        category: BenefitCategory.${cat(b.category)},`)
    out.push(`        icon: ${q(b.icon)},`)
    if (b.merchant) out.push(`        merchant: ${q(b.merchant)},`)
    out.push(`        valueCents: ${b.valueCents},`)
    out.push(`        cadence: Cadence.${b.cadence},`)
    out.push(`        anchor: CycleAnchor.${b.anchor},`)
    if (b.enrollmentRequired) out.push('        enrollmentRequired: true,')
    if (b.redemptionSteps?.length) {
      out.push('        redemptionSteps: [')
      for (const s of b.redemptionSteps) out.push(`          ${q(s)},`)
      out.push('        ],')
    }
    if (b.notes) out.push(`        notes: ${q(b.notes)},`)
    out.push('      ),')
  }
  out.push('    ],')
  out.push('  ),')
}
out.push('];')
out.push('')
out.push('CardTemplate? findTemplate(String id) {')
out.push('  for (final template in cardTemplates) {')
out.push('    if (template.id == id) return template;')
out.push('  }')
out.push('  return null;')
out.push('}')
out.push('')
out.push('/// Total value a template releases in a year, for the catalogue rows.')
out.push('int templateAnnualValueCents(CardTemplate template) {')
out.push(
  '  return template.benefits.fold(0, (sum, b) => sum + b.valueCents * _perYear(b.cadence));',
)
out.push('}')
out.push('')
out.push('int _perYear(Cadence cadence) => switch (cadence) {')
out.push('      Cadence.monthly => 12,')
out.push('      Cadence.quarterly => 4,')
out.push('      Cadence.semiannual => 2,')
out.push('      Cadence.annual => 1,')
out.push('      Cadence.manual => 1,')
out.push('    };')
out.push('')
out.push('/// Credits in a template that are stuck behind an enrolment box.')
out.push('List<String> templateEnrollmentNames(CardTemplate template) {')
out.push(
  '  return template.benefits.where((b) => b.enrollmentRequired).map((b) => b.name).toList();',
)
out.push('}')
out.push('')
out.push('/// Turns a template into real benefits attached to a newly created card.')
out.push('List<Benefit> benefitsFromTemplate(')
out.push('  CardTemplate template,')
out.push('  String cardId,')
out.push('  IsoInstant now,')
out.push('  String Function() newId,')
out.push(') {')
out.push('  return template.benefits')
out.push('      .map((entry) => Benefit(')
out.push('            id: newId(),')
out.push('            cardId: cardId,')
out.push('            name: entry.name,')
out.push('            description: entry.description,')
out.push('            category: entry.category,')
out.push('            icon: entry.icon,')
out.push('            merchant: entry.merchant,')
out.push('            valueCents: entry.valueCents,')
out.push('            cadence: entry.cadence,')
out.push('            anchor: entry.anchor,')
out.push('            enrollmentRequired: entry.enrollmentRequired,')
out.push('            redemptionSteps: entry.redemptionSteps,')
out.push('            notes: entry.notes,')
out.push('            muted: false,')
out.push('            lastCallOnly: false,')
out.push('            active: true,')
out.push('            createdAt: now,')
out.push('            updatedAt: now,')
out.push('          ))')
out.push('      .toList();')
out.push('}')
console.log(out.join('\n'))
